services:
  admin_api:
    container_name: django_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - admin_db
  admin_db:
    container_name: django_admin_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYQSL_DATABASE: django_admin
      MYQSL_USER: rini
      MYQSL_PASSWORD: mypassword
      MYQSL_ROOT_PASSWORD: mypassword
    volumes:
      - .dbdata:/var/lib/mysql