services:
  web:
    container_name: django_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
  db:
    container_name: django_admin_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: django_admin
      MYSQL_USER: rini
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - .dbdata:/var/lib/mysql